apiVersion: v1
kind: Pod

metadata:
  name: fortune-pod
  namespace: default
  labels:
    app.kubernetes.io/name: fortune-pod
    app.kubernetes.io/version: "v1"
    owner: engineering

spec:
  container:
  - name: fortune
    image: chukmunnlee/fortune
    imagePullPolicy: Always
    env:
    - name: APP_PORT
      value: 3000
    port:
    - name: fortune-port
      containerPort: 3000
